name: cross building for beagle bone

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - name: Cache Nonlinux-Dir
      uses: actions/cache@v1
      with:
       path: /home/runner/work/nonlinux
       key: ${{ runner.os }}-nonlinux-${{ github.ref }}
    - uses: actions/checkout@v1
    - name: Clone
      run: git -C /home/runner/work clone https://github.com/nonlinear-labs-dev/nonlinux.git
    - name: Checkout
      run: cd /home/runner/work/nonlinux && git fetch && git checkout project-restructuring 
    - name: Build
      run: cd /home/runner/work/nonlinux && make nonlinear_defconfig && make
    
