name: cross building for beagle bone

on:
  push:
    branches:
      - project-restructuring

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Install Packages
      run: sudo apt-get update -y; sudo apt-get install -y git locales; sudo apt-get update; sudo apt-get install -y git cmake build-essential wget cpio python unzip bc doxygen curl libcurl4-openssl-dev openjdk-8-jdk bash
    
    - name: Cache NonLinux-Prebuilt
      uses: actions/cache@v1
      id: cache-nonlinux-prebuilt
      with:
        path: /home/runner/work/nonlinux-prebuilt
        key: ${{ runner.os }}-nonlinux-prebuilt

    - name: Download Nonlinux Prebuilt
      if: steps.cache-nonlinux-prebuilt.cache-hit != 'true'
      run: mkdir -p /home/runner/work/nonlinux-prebuilt && cd /home/runner/work/nonlinux-prebuilt && wget http://hoegelow.com/nl/nonlinux-prebuilt.zip

    - name: Unpack Nonlinux-Prebuilt
      run: cd /home/runner/work && unzip nonlinux-prebuilt/nonlinux-prebuilt.zip -d ./

    - name: make playground
      run: cd /home/runner/work/nonlinux && make
