name: cross building for beagle bone

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Install Packages
      run: sudo apt-get update -y; sudo apt-get install -y git locales; sudo apt-get update; sudo apt-get install -y git cmake build-essential wget cpio python unzip bc doxygen curl libcurl4-openssl-dev openjdk-8-jdk bash unionfs-fuse squashfuse
    
    - name: Cache NonLinux-Prebuilt
      uses: actions/cache@v1
      id: nonlinux-prebuilt-img
      with:
        path: /home/runner/work/nonlinux-prebuilt
        key: nonlinux-prebuilt-img

    - name: Download Nonlinux Prebuilt
      if: steps.nonlinux-prebuilt-img.outputs.cache-hit != 'true'
      run: mkdir -p /home/runner/work/ && cd /home/runner/work/ && wget http://hoegelow.com/nl/nonlinux-prebuilt.img

    - name: Create overlayfs folders
      run: cd /home/runner/work && mkdir nonlinux nonlinux-squash nonlinux-overlay nonlinux-workdir

    - name: Setup squashfs
      run: cd /home/runner/work && squashfuse nonlinux-prebuilt.img ./nonlinux-squash

    - name: Setup overlayfs
      run: cd /home/runner/work && sudo mount -t overlay -o lowerdir=./nonlinux-squash,upperdir=./nonlinux-overlay,workdir=./nonlinux-workdir none ./nonlinux

    - name: build
      run: cd /home/runner/work/nonlinux && make

