name: cross building for beagle bone

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Install Packages
      run: sudo apt-get update -y; sudo apt-get install -y git locales; sudo apt-get update; sudo apt-get install -y git cmake build-essential wget cpio python unzip bc doxygen curl libcurl4-openssl-dev openjdk-8-jdk bash unionfs-fuse squashfuse
    
    - name: Cache NonLinux-Prebuilt
      uses: actions/cache@v1
      id: nonlinux-prebuilt
      with:
        path: /home/runner/work/dl
        key: nonlinux-prebuilt-img

    - name: Download Nonlinux Prebuilt
      if: steps.nonlinux-prebuilt.outputs.cache-hit != 'true'
      run: mkdir -p /home/runner/work/dl && cd /home/runner/work/dl && wget http://hoegelow.com/nl/nonlinux-prebuilt.img

   

