name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    
    steps:          
    - name: Install Packages
      run: sudo apt-get install libboost-dev libavahi-gobject-dev libasound2-dev libglibmm-2.4-dev uuid-dev libsoup2.4-dev libfreetype6-dev libavahi-glib-dev libavahi-core-dev libavahi-client-dev
    - name: Download GWT
      run: cd /home/runner/work/ && wget https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip 
    - name: unpack GWT  
      run: unzip /home/runner/work/gwt-2.8.2.zip -d /home/runner/work/gwt
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir /home/runner/work/build && cd /home/runner/work/build && cmake /home/runner/work/C15/C15 -DJARSDIR=/home/runner/work/gwt/gwt-2.8.2
    - name: make
      run: cd /home/runner/work/build && make -j4 -l4 install
