name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir /home/runner/work/build && cd /home/runner/work/build && cmake /home/runner/work/C15
    - name: make
      run: make
