name: epc-Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install ccache

    - name: Configure
      run: |
        mkdir -p /home/runner/work/build
        cd /home/runner/work/build
        ls -lah /home/runner/work
        echo "AAAA"
        ls -lah /home/runner/work/C15
        echo "BBBB"
        ls -lah /home/runner/work/C15/C15
        cmake /home/runner/work/C15/C15 -DBUILD_EPC=On

    - name: Make
      run: |
        cd /home/runner/work/build
        echo "here we would have to call 'make epc-update'"
