name: epc-Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: |
        mkdir -p /home/runner/work/build
        cd /home/runner/work/build
        cmake -DBUILD_EPC=On /home/runner/work/C15/C15

    - name: Make
      run: make -C /home/runner/work/build epc-create-update
