name: x86-Build

on:
  push:
    branches:
      - master-disabled

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install ccache libboost-dev libavahi-gobject-dev libasound2-dev libglibmm-2.4-dev uuid-dev libsoup2.4-dev libfreetype6-dev libavahi-glib-dev libavahi-core-dev libavahi-client-dev

    - name: Cache GWT
      uses: actions/cache@v1
      id: cache-gwt
      with:
        path: /home/runner/work/gwt/gwt-2.8.2
        key: ${{ runner.os }}-gwt-2.8.2
    
    - name: Cache CCache
      uses: actions/cache@v1
      with:
        path: /home/runner/.ccache
        key: ${{ runner.os }}-ccache-${{ github.ref }}
    
    - name: Download GWT
      if: steps.cache-gwt.outputs.cache-hit != 'true'
      run: cd /home/runner/work/ && wget https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip 
    
    - name: Unpack GWT  
      if: steps.cache-gwt.outputs.cache-hit != 'true'
      run: unzip /home/runner/work/gwt-2.8.2.zip -d /home/runner/work/gwt
    - uses: actions/checkout@v1

    - name: Configure
      run: mkdir -p /home/runner/work/build && cd /home/runner/work/build && cmake /home/runner/work/C15/C15 -DJARSDIR=/home/runner/work/gwt/gwt-2.8.2 -DBUILD_BBB=On -DCMAKE_INSTALL_PREFIX=/home/runner/work/out

    - name: Make
      run: cd /home/runner/work/build && make -j4 install

    - name: Run tests
      run: cd /home/runner/work/build && make test

    - name: Pack artifacts
      uses: actions/upload-artifact@v1
      with:
        name: C15-build
        path: /home/runner/work/out/
